language: java
before_install:
  - unset SORCER_HOME
  - export SORCER_HOME=`pwd`
  - echo "SORCER_HOME is $SORCER_HOME"
install: mvn -q install
before_script:
  - $SORCER_HOME/bin/sorcer-boot & sleep 10
script: cd $SORCER_HOME/sos/sos-tests/ && mvn -Djava.net.preferIPv4Stack=true -Dmaven.test.skip=false test
jdk:
#  - openjdk6
#  - openjdk7
  - oraclejdk7
# whitelist
branches:
  only:
    - master

notifications:
  email:
    - pawel.rubach@sorcersoft.com
