language: java
before_install:
  - unset SORCER_HOME
  - export SORCER_HOME=`pwd`
  - echo "SORCER_HOME is $SORCER_HOME"    
script: mvn -Dmaven.test.skip=false test
jdk:
#  - openjdk6
#  - openjdk7
  - oraclejdk7
# whitelist
branches:
  only:
    - master

notifications:
  email:
    - pawel.rubach@sorcersoft.com
