language: java
before_install:
  - unset SORCER_HOME
  - export SORCER_HOME=`pwd`
  - echo "SORCER_HOME is $SORCER_HOME"
  - ifconfig
  - cat /etc/hosts
  - hostname
install: mvn -q install
before_script:
#  - cp -f $SORCER_HOME/configs/template/sorcer.env_int-tests $SORCER_HOME/configs/sorcer.env
#  - export JAVA_OPTS=-Djava.net.preferIPv6Stack=true
  - $SORCER_HOME/bin/sorcer-boot &
  - sleep 10
script: cd $SORCER_HOME/sos/sos-tests/ && mvn -Dmaven.test.skip=false test
jdk:
#  - openjdk6
#  - openjdk7
  - oraclejdk7
# whitelist
branches:
  only:
    - master

notifications:
  email:
    - sorcer-devel@lists.sourceforge.net
